"""Create Unique Constraint on user and user_meta tables.

Revision ID: 048106f9d043
Revises: 54fb8d090549
Create Date: 2023-06-17 11:06:14.771761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048106f9d043'
down_revision = '54fb8d090549'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_user_id", 'user', ['id'])
    op.create_unique_constraint("uq_user_meta_id", 'user_meta', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_id", 'user_meta', type_='unique')
    op.drop_constraint("uq_user_meta_id", 'user', type_='unique')
    # ### end Alembic commands ###
