#!/usr/bin/env python

"""SQLAlchemy model for the claim communication table — Carrier Messages, Client Messages, Internal Notes"""

from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import ForeignKey, Index, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base
from app.db.mixins import AuditMixin, SoftDeleteMixin, TimestampMixin

if TYPE_CHECKING:
    from app.models import Claim, User


class ClaimCommunication(SoftDeleteMixin, TimestampMixin, AuditMixin, Base):
    __tablename__ = "claim_communication"

    # Foreign Keys
    claim_id: Mapped[UUID] = mapped_column(
        ForeignKey("claim.id", name="fk_claim_comm_claim_id", ondelete="CASCADE")
    )
    sender_id: Mapped[UUID] = mapped_column(
        ForeignKey("user.id", name="fk_claim_comm_sender_id", ondelete="CASCADE")
    )

    # Message classification: "carrier", "client", "internal"
    message_type: Mapped[str] = mapped_column(String(20))

    # Content
    subject: Mapped[str | None] = mapped_column(String(500), nullable=True)
    body: Mapped[str] = mapped_column(Text())

    # For carrier messages
    recipient_email: Mapped[str | None] = mapped_column(String(255), nullable=True)
    recipient_name: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Direction: "inbound" or "outbound"
    direction: Mapped[str] = mapped_column(String(10), default="outbound")

    # Channel: "email", "portal", "note", "system"
    channel: Mapped[str] = mapped_column(String(20), default="portal")

    # Threading for client messages
    thread_id: Mapped[UUID | None] = mapped_column(
        ForeignKey(
            "claim_communication.id",
            name="fk_claim_comm_thread_id",
            ondelete="SET NULL",
        ),
        nullable=True,
    )

    # Whether this was auto-generated by the system (supplement email, etc.)
    is_system_generated: Mapped[bool] = mapped_column(default=False)

    # Attachments stored as JSON string: [{"file_id": "...", "filename": "..."}]
    attachments_json: Mapped[str | None] = mapped_column(Text(), nullable=True)

    # Relationships
    claim: Mapped["Claim"] = relationship(
        back_populates="claim_communications",
        lazy="joined",
        viewonly=True,
        join_depth=1,
    )
    sender: Mapped["User"] = relationship(
        primaryjoin="ClaimCommunication.sender_id == User.id",
        lazy="joined",
        viewonly=True,
        join_depth=2,
    )
    replies: Mapped[list["ClaimCommunication"]] = relationship(
        primaryjoin="ClaimCommunication.id == foreign(ClaimCommunication.thread_id)",
        viewonly=True,
    )

    __table_args__ = (
        Index("ix_claim_comm_claim_type", "claim_id", "message_type"),
        Index("ix_claim_comm_sender", "sender_id"),
        Index("ix_claim_comm_thread", "thread_id"),
    )

    def __repr__(self) -> str:
        return (
            f"ClaimCommunication(id={self.id!r}, claim_id={self.claim_id!r}, "
            f"message_type={self.message_type!r}, channel={self.channel!r})"
        )
