"""
Create User Policy and Policy Permission tables.

Revision ID: 0702431c1065
Revises: 16a67549a22f
Create Date: 2023-11-28 13:16:51.507615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0702431c1065'
down_revision = '16a67549a22f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_policy',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_user_policy_created_by_id'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='fk_user_policy_updated_by_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_policy_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('policy_permission',
    sa.Column('effect', sa.String(length=30), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name='fk_policy_permission_permission_id'),
    sa.ForeignKeyConstraint(['policy_id'], ['user_policy.id'], name='fk_policy_permission_policy_id'),
    sa.PrimaryKeyConstraint('policy_id', 'permission_id', 'id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_permission')
    op.drop_table('user_policy')
    # ### end Alembic commands ###
