"""
Add columns to a claim table.

Revision ID: 08ca46ffb4bc
Revises: 14707ea696fd
Create Date: 2023-11-02 12:18:25.772721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ca46ffb4bc'
down_revision = '14707ea696fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('anticipated_amount', sa.Float(), nullable=True))
    op.add_column('claim', sa.Column('signed_by', sa.String(length=100), nullable=True))
    op.add_column('claim', sa.Column('adjusted_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'adjusted_by')
    op.drop_column('claim', 'signed_by')
    op.drop_column('claim', 'anticipated_amount')
    # ### end Alembic commands ###
