"""
Create Newsletter and Newsletter Tags tables.

Revision ID: 0dcf7ae09211
Revises: 46cb61e8ec92
Create Date: 2023-10-06 19:21:14.957930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dcf7ae09211'
down_revision = '46cb61e8ec92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('can_be_removed', sa.Boolean(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_newsletter_created_by_id'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='fk_newsletter_updated_by_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('newsletter_tag',
    sa.Column('newsletter_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletter.id'], name='fk_newsletter_tag_newsletter_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='fk_newsletter_tag_tag_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('newsletter_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletter_tag')
    op.drop_table('newsletter')
    # ### end Alembic commands ###
