"""
Create Claim Payment File table.

Revision ID: 10fbe5cbcb06
Revises: 7a57aa1c5734
Create Date: 2024-08-18 14:32:56.498692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10fbe5cbcb06'
down_revision = '7a57aa1c5734'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_payment_file',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['file.id'], name='fk_claim_payment_file_id'),
    sa.ForeignKeyConstraint(['payment_id'], ['claim_payment.id'], name='fk_claim_payment_file_payment_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_payment_file')
    # ### end Alembic commands ###
