"""
Create a table Claim Payment.

Revision ID: 14707ea696fd
Revises: 9cee016ce084
Create Date: 2023-10-18 13:19:43.067924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14707ea696fd'
down_revision = '9cee016ce084'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_payment',
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('ref_number', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name='fk_claim_payment_claim_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_claim_payment_created_by_id'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='fk_claim_payment_updated_by_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_payment')
    # ### end Alembic commands ###
