"""
Add columns to the claim payment table.

Revision ID: 16a67549a22f
Revises: 08ca46ffb4bc
Create Date: 2023-11-04 16:34:16.859869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a67549a22f'
down_revision = '08ca46ffb4bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_payment', sa.Column('income_type', sa.String(length=50), nullable=True))
    op.add_column('claim_payment', sa.Column('expense_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_payment', 'expense_type')
    op.drop_column('claim_payment', 'income_type')
    # ### end Alembic commands ###
