"""
Create a Network table.

Revision ID: 18d135d73ec8
Revises: b42c042c8377
Create Date: 2023-08-31 11:44:43.014444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d135d73ec8'
down_revision = 'b42c042c8377'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('key_elements', sa.Text(), nullable=False),
    sa.Column('exploration_type', sa.String(length=20), nullable=False),
    sa.Column('exploration_term', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_be_removed', sa.Boolean(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_network_created_by_id'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='fk_network_updated_by_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('network')
    # ### end Alembic commands ###
