"""
Add Manager ID and relation key to the User table.

Revision ID: 1fcca9990f31
Revises: 10fbe5cbcb06
Create Date: 2024-08-25 07:39:02.438532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fcca9990f31'
down_revision = '10fbe5cbcb06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_user_manager_id', 'user', 'user', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_manager_id', 'user', type_='foreignkey')
    op.drop_column('user', 'manager_id')
    # ### end Alembic commands ###
