"""
Add new columns to the Client and Claim table.

Revision ID: 20ec4f11f5af
Revises: ddb7c81fbb7c
Create Date: 2024-02-19 18:42:28.660461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ec4f11f5af'
down_revision = 'ddb7c81fbb7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('policy_type', sa.String(length=100), nullable=True))
    op.add_column('claim', sa.Column('date_logged', sa.Date(), nullable=True))
    op.add_column('client', sa.Column('organization', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'organization')
    op.drop_column('claim', 'date_logged')
    op.drop_column('claim', 'policy_type')
    # ### end Alembic commands ###
