"""Create Claim File Share Tables

Revision ID: 21cbb3ac45b3
Revises: d4ba687ad171
Create Date: 2024-05-20 23:48:47.045265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cbb3ac45b3'
down_revision = 'd4ba687ad171'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_file_share',
    sa.Column('email_files_to', sa.String(), nullable=False),
    sa.Column('share_type', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('claim_file_share_details',
    sa.Column('claim_file_id', sa.UUID(), nullable=False),
    sa.Column('share_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['share_id'], ['claim_file_share.id'], ),
    sa.PrimaryKeyConstraint('claim_file_id', 'share_id', 'id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_file_share_details')
    op.drop_table('claim_file_share')
    # ### end Alembic commands ###
