"""Create storm intelligence tables

Revision ID: 220885b760da
Revises: 77b13214f1a8
Create Date: 2026-03-05 16:10:53.571292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '220885b760da'
down_revision = '77b13214f1a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storm_event',
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_miles', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('zip_codes', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hail_size_inches', sa.Float(), nullable=True),
    sa.Column('wind_speed_mph', sa.Float(), nullable=True),
    sa.Column('gust_speed_mph', sa.Float(), nullable=True),
    sa.Column('hurricane_category', sa.Integer(), nullable=True),
    sa.Column('hurricane_name', sa.String(length=100), nullable=True),
    sa.Column('track_points', sa.Text(), nullable=True),
    sa.Column('strike_count', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source', 'external_id', name='uq_storm_event_source_external')
    )
    op.create_index(op.f('ix_storm_event_county'), 'storm_event', ['county'], unique=False)
    op.create_index(op.f('ix_storm_event_data_source'), 'storm_event', ['data_source'], unique=False)
    op.create_index(op.f('ix_storm_event_event_type'), 'storm_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_storm_event_external_id'), 'storm_event', ['external_id'], unique=False)
    op.create_index(op.f('ix_storm_event_severity'), 'storm_event', ['severity'], unique=False)
    op.create_index(op.f('ix_storm_event_state'), 'storm_event', ['state'], unique=False)
    op.create_table('storm_outreach_batch',
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_codes', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('estimated_properties', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_storm_outreach_batch_created_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.drop_constraint('uq_call_type_config_code', 'call_type_config', type_='unique')
    op.drop_index('ix_call_type_config_code', table_name='call_type_config')
    op.create_index(op.f('ix_call_type_config_code'), 'call_type_config', ['code'], unique=True)
    op.alter_column('fire_data_source_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('pricing_item_code_key', 'pricing_item', type_='unique')
    op.create_unique_constraint('uq_pricing_item_code', 'pricing_item', ['code'])
    op.alter_column('property_intelligence', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('rin_source', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rin_source', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('property_intelligence', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint('uq_pricing_item_code', 'pricing_item', type_='unique')
    op.create_unique_constraint('pricing_item_code_key', 'pricing_item', ['code'])
    op.alter_column('fire_data_source_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_call_type_config_code'), table_name='call_type_config')
    op.create_index('ix_call_type_config_code', 'call_type_config', ['code'], unique=False)
    op.create_unique_constraint('uq_call_type_config_code', 'call_type_config', ['code'])
    op.drop_table('storm_outreach_batch')
    op.drop_index(op.f('ix_storm_event_state'), table_name='storm_event')
    op.drop_index(op.f('ix_storm_event_severity'), table_name='storm_event')
    op.drop_index(op.f('ix_storm_event_external_id'), table_name='storm_event')
    op.drop_index(op.f('ix_storm_event_event_type'), table_name='storm_event')
    op.drop_index(op.f('ix_storm_event_data_source'), table_name='storm_event')
    op.drop_index(op.f('ix_storm_event_county'), table_name='storm_event')
    op.drop_table('storm_event')
    # ### end Alembic commands ###
