"""
Create a Lead File table.

Revision ID: 2765cfe40281
Revises: 7e60169d6b01
Create Date: 2023-08-17 21:24:47.160739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2765cfe40281'
down_revision = '7e60169d6b01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_file',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['file.id'], name='fk_lead_file_id'),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], name='fk_lead_file_lead_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_file')
    # ### end Alembic commands ###
