"""
Add the client_id column to the Lead table,
Create a foreign key for the client_id column.

Revision ID: 28ec2678e5c5
Revises: 18d135d73ec8
Create Date: 2023-09-03 08:04:26.811138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ec2678e5c5'
down_revision = '18d135d73ec8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_lead_client_id', 'lead', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_lead_client_id', 'lead', type_='foreignkey')
    op.drop_column('lead', 'client_id')
    # ### end Alembic commands ###
