"""
Add foreign key for lead user under lead table.

Revision ID: 32e5974e9f66
Revises: cf2c3bcf5d46
Create Date: 2024-10-15 19:37:43.796837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e5974e9f66'
down_revision = 'cf2c3bcf5d46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('lead_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_lead_user_id', 'lead', 'user', ['lead_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_lead_user_id', 'lead', type_='foreignkey')
    op.drop_column('lead', 'lead_user_id')
    # ### end Alembic commands ###
