"""
Create a business email table.

Revision ID: 344405662316
Revises: 0702431c1065
Create Date: 2024-02-05 07:41:26.367977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344405662316'
down_revision = '0702431c1065'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_email',
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=75), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('related_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name='fk_claim_business_email_claim_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_email')
    # ### end Alembic commands ###
