"""
Create Claim Coverage table,
Add a new Sub Policy Type column in the Claim table.

Revision ID: 3bc95734f6ba
Revises: df42d462acd2
Create Date: 2024-07-03 13:27:23.708661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc95734f6ba'
down_revision = 'df42d462acd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_coverage',
    sa.Column('coverage_type', sa.String(length=255), nullable=False),
    sa.Column('policy_limit', sa.Float(), nullable=True),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name='fk_claim_coverage_claim_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.add_column('claim', sa.Column('sub_policy_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'sub_policy_type')
    op.drop_table('claim_coverage')
    # ### end Alembic commands ###
