"""
Add more columns to the claim table.

Revision ID: 3df5164b9f31
Revises: 4664d37db095
Create Date: 2024-06-15 19:42:58.184975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df5164b9f31'
down_revision = '4664d37db095'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('lawsuit_deadline', sa.Date(), nullable=True))
    op.add_column('claim', sa.Column('mortgage_company', sa.String(length=100), nullable=True))
    op.add_column('claim', sa.Column('fema_claim', sa.Boolean(), nullable=True))
    op.add_column('claim', sa.Column('state_of_emergency', sa.Boolean(), nullable=True))
    op.add_column('claim', sa.Column('inhabitable', sa.Boolean(), nullable=True))
    op.add_column('claim', sa.Column('contract_sign_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'contract_sign_date')
    op.drop_column('claim', 'inhabitable')
    op.drop_column('claim', 'state_of_emergency')
    op.drop_column('claim', 'fema_claim')
    op.drop_column('claim', 'mortgage_company')
    op.drop_column('claim', 'lawsuit_deadline')
    # ### end Alembic commands ###
