"""
Create a NPO Initiative table.

Revision ID: 40c9f204f3c6
Revises: 411a327610dc
Create Date: 2023-08-17 22:08:39.895256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c9f204f3c6'
down_revision = '411a327610dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('npo_initiative',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('mission', sa.Text(), nullable=False),
    sa.Column('key_elements', sa.Text(), nullable=False),
    sa.Column('search_term', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_be_removed', sa.Boolean(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_npo_initiative_created_by_id'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='fk_npo_initiative_updated_by_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('npo_initiative')
    # ### end Alembic commands ###
