"""
Create a Lead Comment table.

Revision ID: 411a327610dc
Revises: 6ce4b3826e17
Create Date: 2023-08-17 21:42:53.175597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411a327610dc'
down_revision = '6ce4b3826e17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_comment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['comment.id'], name='fk_lead_comment_id'),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], name='fk_lead_comment_lead_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_comment')
    # ### end Alembic commands ###
