"""

Update column-type from Str to UUID of source, signed_by, and adjusted_by columns in the claim table.

Revision ID: 4664d37db095
Revises: 8c041318133b
Create Date: 2024-06-15 08:50:57.479570

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4664d37db095"
down_revision = "8c041318133b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("claim", sa.Column("source_temp", sa.UUID(), nullable=True))
    op.drop_column("claim", "source")
    op.alter_column(
        "claim", "source_temp", new_column_name="source", existing_type=sa.UUID()
    )
    op.add_column("claim", sa.Column("signed_by_temp", sa.UUID(), nullable=True))
    op.drop_column("claim", "signed_by")
    op.alter_column(
        "claim", "signed_by_temp", new_column_name="signed_by", existing_type=sa.UUID()
    )
    op.add_column("claim", sa.Column("adjusted_by_temp", sa.UUID(), nullable=True))
    op.drop_column("claim", "adjusted_by")
    op.alter_column(
        "claim",
        "adjusted_by_temp",
        new_column_name="adjusted_by",
        existing_type=sa.UUID(),
    )
    op.create_foreign_key(
        "fk_claim_source", "claim", "user", ["source"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "fk_claim_signed_by", "claim", "user", ["signed_by"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "fk_claim_adjusted_by",
        "claim",
        "user",
        ["adjusted_by"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_claim_adjusted_by", "claim", type_="foreignkey")
    op.drop_constraint("fk_claim_signed_by", "claim", type_="foreignkey")
    op.drop_constraint("fk_claim_source", "claim", type_="foreignkey")
    op.add_column(
        "claim", sa.Column("adjusted_by_temp", sa.String(length=100), nullable=True)
    )
    op.drop_column("claim", "adjusted_by")
    op.alter_column(
        "claim",
        "adjusted_by_temp",
        new_column_name="adjusted_by",
        existing_type=sa.String(length=100),
    )
    op.add_column(
        "claim", sa.Column("signed_by_temp", sa.String(length=100), nullable=True)
    )
    op.drop_column("claim", "signed_by")
    op.alter_column(
        "claim",
        "signed_by_temp",
        new_column_name="signed_by",
        existing_type=sa.String(length=100),
    )
    op.add_column(
        "claim", sa.Column("source_temp", sa.String(length=30), nullable=True)
    )
    op.drop_column("claim", "source")
    op.alter_column(
        "claim",
        "source_temp",
        new_column_name="source",
        existing_type=sa.String(length=30),
    )
    # ### end Alembic commands ###
