"""
Create a Daily Schedule table.

Revision ID: 46cb61e8ec92
Revises: 90eece773cbc
Create Date: 2023-09-16 09:50:43.379028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46cb61e8ec92'
down_revision = '90eece773cbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user_task.id'], name='fk_daily_schedule_id'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name='fk_daily_schedule_schedule_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_schedule')
    # ### end Alembic commands ###
