"""
Add Parent ID and relation key to the User table.

Revision ID: 583d7a2d08ee
Revises: 1fcca9990f31
Create Date: 2024-09-12 12:13:34.753324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583d7a2d08ee'
down_revision = '1fcca9990f31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_user_parent_id', 'user', 'user', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_parent_id', 'user', type_='foreignkey')
    op.drop_column('user', 'parent_id')
    # ### end Alembic commands ###
