"""
Update File table column type length.

Revision ID: 5b51755845c9
Revises: 20ec4f11f5af
Create Date: 2024-02-22 17:23:14.985815

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b51755845c9"
down_revision = "20ec4f11f5af"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file", "type", existing_type=sa.VARCHAR(length=50), type_=sa.String(length=150)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file", "type", existing_type=sa.VARCHAR(length=150), type_=sa.String(length=50)
    )
    # ### end Alembic commands ###
