"""
Append slug field for file table.

Revision ID: 5f64f38b3836
Revises: 998a253fef4f
Create Date: 2024-03-12 13:40:11.643342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f64f38b3836'
down_revision = '998a253fef4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('slugged_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'slugged_name')
    # ### end Alembic commands ###
