"""
Add/Drop columns to a claim payment table.

Revision ID: 66ff020885ee
Revises: ea8a94ed109c
Create Date: 2024-07-30 16:03:12.205062

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "66ff020885ee"
down_revision = "ea8a94ed109c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add the check_amount column allowing NULL values
    op.add_column(
        "claim_payment",
        sa.Column("check_amount", sa.Float(), nullable=True),
    )
    # Update existing rows to set a default value
    op.execute("UPDATE claim_payment SET check_amount = 0.0 WHERE check_amount IS NULL")
    # Alter the column to disallow NULL values
    op.alter_column("claim_payment", "check_amount", nullable=False)

    # Add the contingency_fee_percentage column allowing NULL values
    op.add_column(
        "claim_payment",
        sa.Column("contingency_fee_percentage", sa.Float(), nullable=True),
    )
    # Update existing rows to set a default value
    op.execute(
        "UPDATE claim_payment SET contingency_fee_percentage = 0.0 WHERE contingency_fee_percentage IS NULL"
    )
    # Alter the column to disallow NULL values
    op.alter_column("claim_payment", "contingency_fee_percentage", nullable=False)

    op.add_column(
        "claim_payment", sa.Column("appraisal_fee", sa.Float(), nullable=True)
    )
    op.add_column("claim_payment", sa.Column("umpire_fee", sa.Float(), nullable=True))
    op.add_column("claim_payment", sa.Column("mold_fee", sa.Float(), nullable=True))
    op.add_column("claim_payment", sa.Column("misc_fee", sa.Float(), nullable=True))

    # Add the is_locked column allowing NULL values
    op.add_column(
        "claim_payment",
        sa.Column("is_locked", sa.Boolean(), nullable=True),
    )
    # Update existing rows to set a default value
    op.execute("UPDATE claim_payment SET is_locked = 'false' WHERE is_locked IS NULL")
    # Alter the column to disallow NULL values
    op.alter_column("claim_payment", "is_locked", nullable=False)

    op.drop_column("claim_payment", "payment_type")
    op.drop_column("claim_payment", "expense_type")
    op.drop_column("claim_payment", "income_type")
    op.drop_column("claim_payment", "amount")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add the amount column allowing NULL values
    op.add_column(
        "claim_payment",
        sa.Column("amount", sa.Float(), nullable=True),
    )
    # Update existing rows to set a default value
    op.execute("UPDATE claim_payment SET amount = 0.0 WHERE amount IS NULL")
    # Alter the column to disallow NULL values
    op.alter_column("claim_payment", "amount", nullable=False)

    op.add_column(
        "claim_payment",
        sa.Column(
            "income_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "claim_payment",
        sa.Column(
            "expense_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )

    # Add the payment_type column allowing NULL values
    op.add_column(
        "claim_payment",
        sa.Column(
            "payment_type", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
    )
    # Update existing rows to set a default value
    op.execute(
        "UPDATE claim_payment SET payment_type = 'debit' WHERE payment_type IS NULL"
    )
    # Alter the column to disallow NULL values
    op.alter_column("claim_payment", "payment_type", nullable=False)

    op.drop_column("claim_payment", "is_locked")
    op.drop_column("claim_payment", "misc_fee")
    op.drop_column("claim_payment", "mold_fee")
    op.drop_column("claim_payment", "umpire_fee")
    op.drop_column("claim_payment", "appraisal_fee")
    op.drop_column("claim_payment", "contingency_fee_percentage")
    op.drop_column("claim_payment", "check_amount")
    # ### end Alembic commands ###
