"""
Create Schedule and Schedule Task tables.

Revision ID: 69992d52a385
Revises: 5a3972e01a6b
Create Date: 2023-08-17 20:34:42.036763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69992d52a385'
down_revision = '5a3972e01a6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('goal', sa.String(length=255), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_be_removed', sa.Boolean(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_schedule_created_by_id'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='fk_schedule_updated_by_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_number', name='uq_schedule_day')
    )
    op.create_table('schedule_task',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name='fk_schedule_task_schedule_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='fk_schedule_task_task_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id', 'task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_task')
    op.drop_table('schedule')
    # ### end Alembic commands ###
