"""
Create a Newsletter File table.

Revision ID: 73298e7dc7cf
Revises: 0dcf7ae09211
Create Date: 2023-10-07 08:43:26.990475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73298e7dc7cf'
down_revision = '0dcf7ae09211'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_file',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('newsletter_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['file.id'], name='fk_newsletter_file_id'),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletter.id'], name='fk_newsletter_file_newsletter_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletter_file')
    # ### end Alembic commands ###
