"""
Add the Check Type and Is Ready To Process columns to the Claim Payment table.

Revision ID: 7a57aa1c5734
Revises: 66ff020885ee
Create Date: 2024-08-03 19:07:17.454496

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a57aa1c5734"
down_revision = "66ff020885ee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the check_type column allowing NULL values
    op.add_column(
        "claim_payment", sa.Column("check_type", sa.String(length=20), nullable=True)
    )
    # Update existing rows to set a default value
    op.execute(
        "UPDATE claim_payment SET check_type = 'standard' WHERE check_type IS NULL"
    )
    # Alter the column to disallow NULL values
    op.alter_column("claim_payment", "check_type", nullable=False)

    # Add the is_ready_to_process column allowing NULL values
    op.add_column(
        "claim_payment",
        sa.Column("is_ready_to_process", sa.Boolean(), nullable=True),
    )
    # Update existing rows to set a default value
    op.execute(
        "UPDATE claim_payment SET is_ready_to_process = 'false' WHERE is_ready_to_process IS NULL"
    )
    # Alter the column to disallow NULL values
    op.alter_column("claim_payment", "is_ready_to_process", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("claim_payment", "is_ready_to_process")
    op.drop_column("claim_payment", "check_type")
    # ### end Alembic commands ###
