"""
Create Role, Permission and Role Permission tables,
Add related constraints and columns in the User table.

Revision ID: 863e35c5778d
Revises: 2ff3193dc6e8
Create Date: 2023-08-17 11:21:39.570067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863e35c5778d'
down_revision = '2ff3193dc6e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('can_be_removed', sa.Boolean(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_role_created_by_id'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='fk_role_updated_by_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('permission',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('can_be_removed', sa.Boolean(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_permission_created_by_id'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='fk_permission_updated_by_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name='fk_role_permission_permission_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='fk_role_permission_role_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.add_column('user', sa.Column('role_id', sa.UUID(), nullable=False))
    op.create_foreign_key('fk_user_role_id', 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_role_id', 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_table('role_permission')
    op.drop_table('permission')
    op.drop_table('role')
    # ### end Alembic commands ###
