"""
Create a Claim Comment table.

Revision ID: 8b71e848dd03
Revises: d9e4934aad3c
Create Date: 2023-09-07 08:25:39.901052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b71e848dd03'
down_revision = 'd9e4934aad3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_comment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name='fk_claim_comment_claim_id'),
    sa.ForeignKeyConstraint(['id'], ['comment.id'], name='fk_claim_comment_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_comment')
    # ### end Alembic commands ###
