"""
Add Phone Number Extension Column to the User table.

Revision ID: 8c041318133b
Revises: 21cbb3ac45b3
Create Date: 2024-05-24 07:14:15.947270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c041318133b'
down_revision = '21cbb3ac45b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_meta', sa.Column('phone_number_extension', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_meta', 'phone_number_extension')
    # ### end Alembic commands ###
