"""
Create a Claim Task table.

Revision ID: 90eece773cbc
Revises: dc1949bd4fd6
Create Date: 2023-09-10 08:05:07.532013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90eece773cbc'
down_revision = 'dc1949bd4fd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name='fk_claim_task_claim_id'),
    sa.ForeignKeyConstraint(['id'], ['user_task.id'], name='fk_claim_task_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_task')
    # ### end Alembic commands ###
