"""add_carrier_comparison_tables

Revision ID: 94fe22eb3b9e
Revises: a7b8c9d0e1f2
Create Date: 2026-03-12 22:32:05.218431

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '94fe22eb3b9e'
down_revision = 'a7b8c9d0e1f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier_estimate',
    sa.Column('carrier_name', sa.String(length=200), nullable=False),
    sa.Column('upload_type', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_key', sa.String(length=500), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='parsed', nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_carrier_estimate_created_by_id'),
    sa.ForeignKeyConstraint(['project_id'], ['estimate_project.id'], name='fk_carrier_estimate_project_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='fk_carrier_estimate_updated_by_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_carrier_estimate_project_id'), 'carrier_estimate', ['project_id'], unique=False)
    op.create_table('carrier_comparison',
    sa.Column('comparison_data', sa.Text(), nullable=True),
    sa.Column('price_threshold', sa.Float(), nullable=False),
    sa.Column('aci_total', sa.Float(), nullable=True),
    sa.Column('carrier_total', sa.Float(), nullable=True),
    sa.Column('supplement_total', sa.Float(), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('aci_only_count', sa.Integer(), nullable=False),
    sa.Column('carrier_only_count', sa.Integer(), nullable=False),
    sa.Column('price_diff_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='completed', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('carrier_estimate_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_estimate_id'], ['carrier_estimate.id'], name='fk_carrier_comparison_carrier_estimate_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_carrier_comparison_created_by_id'),
    sa.ForeignKeyConstraint(['project_id'], ['estimate_project.id'], name='fk_carrier_comparison_project_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='fk_carrier_comparison_updated_by_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_carrier_comparison_carrier_estimate_id'), 'carrier_comparison', ['carrier_estimate_id'], unique=False)
    op.create_index(op.f('ix_carrier_comparison_project_id'), 'carrier_comparison', ['project_id'], unique=False)
    op.create_table('carrier_line_item',
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('room_name', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('carrier_estimate_id', sa.UUID(), nullable=False),
    sa.Column('matched_room_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_estimate_id'], ['carrier_estimate.id'], name='fk_carrier_line_item_carrier_estimate_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_room_id'], ['estimate_room.id'], name='fk_carrier_line_item_matched_room_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_carrier_line_item_carrier_estimate_id'), 'carrier_line_item', ['carrier_estimate_id'], unique=False)
    op.create_index(op.f('ix_carrier_line_item_matched_room_id'), 'carrier_line_item', ['matched_room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carrier_line_item_matched_room_id'), table_name='carrier_line_item')
    op.drop_index(op.f('ix_carrier_line_item_carrier_estimate_id'), table_name='carrier_line_item')
    op.drop_table('carrier_line_item')
    op.drop_index(op.f('ix_carrier_comparison_project_id'), table_name='carrier_comparison')
    op.drop_index(op.f('ix_carrier_comparison_carrier_estimate_id'), table_name='carrier_comparison')
    op.drop_table('carrier_comparison')
    op.drop_index(op.f('ix_carrier_estimate_project_id'), table_name='carrier_estimate')
    op.drop_table('carrier_estimate')
    # ### end Alembic commands ###
