"""
Add a unique constraint to the business email table.

Revision ID: 998a253fef4f
Revises: 5b51755845c9
Create Date: 2024-03-08 18:21:54.722818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998a253fef4f'
down_revision = '5b51755845c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_business_email_email', 'business_email', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_business_email_email', 'business_email', type_='unique')
    # ### end Alembic commands ###
