"""
Create a Claim Activity table.

Revision ID: 9cee016ce084
Revises: 9dfa457c1917
Create Date: 2023-10-14 10:15:21.234231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cee016ce084'
down_revision = '9dfa457c1917'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name='fk_claim_activity_claim_id'),
    sa.ForeignKeyConstraint(['id'], ['user_activity.id'], name='fk_claim_activity_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_activity')
    # ### end Alembic commands ###
