"""
Create User Activity and Announcement Activity tables,
Update Announcement and Newsletters tables.

Revision ID: 9dfa457c1917
Revises: 6a2c953b94a5
Create Date: 2023-10-12 18:07:31.878454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfa457c1917'
down_revision = '6a2c953b94a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('related_type', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_user_activity_created_by_id'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='fk_user_activity_updated_by_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_activity_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('announcement_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcement.id'], name='fk_announcement_activity_announcement_id'),
    sa.ForeignKeyConstraint(['id'], ['user_activity.id'], name='fk_announcement_activity_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('announcement', 'announcement_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('announcement', 'expiration_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('newsletter', 'publication_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newsletter', 'publication_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('announcement', 'expiration_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('announcement', 'announcement_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_table('announcement_activity')
    op.drop_table('user_activity')
    # ### end Alembic commands ###
