"""Add default columns is_removed, can_be_removed to tables.

Revision ID: a8dcf9a4d32f
Revises: 048106f9d043
Create Date: 2023-06-30 14:05:21.476695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8dcf9a4d32f'
down_revision = '048106f9d043'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('can_be_removed', sa.Boolean(), nullable=True))
    op.execute("UPDATE permission SET can_be_removed = false")
    op.alter_column('permission', 'can_be_removed', nullable=False)

    op.add_column('permission', sa.Column('is_removed', sa.Boolean(), nullable=True))
    op.execute("UPDATE permission SET is_removed = false")
    op.alter_column('permission', 'is_removed', nullable=False)

    op.add_column('role', sa.Column('is_removed', sa.Boolean(), nullable=True))
    op.execute("UPDATE role SET is_removed = false")
    op.alter_column('role', 'is_removed', nullable=False)

    op.drop_column('user', 'token')
    op.drop_column('user', 'verified_at')
    op.drop_column('user', 'pass_reset_token_expiry')

    op.add_column('user_meta', sa.Column('can_be_removed', sa.Boolean(), nullable=True))
    op.execute("UPDATE user_meta SET can_be_removed = false")
    op.alter_column('user_meta', 'can_be_removed', nullable=False)

    op.add_column('user_meta', sa.Column('is_removed', sa.Boolean(), nullable=True))
    op.execute("UPDATE user_meta SET is_removed = false")
    op.alter_column('user_meta', 'is_removed', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_meta', 'is_removed')
    op.drop_column('user_meta', 'can_be_removed')
    op.add_column('user', sa.Column('pass_reset_token_expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('role', 'is_removed')
    op.drop_column('permission', 'is_removed')
    op.drop_column('permission', 'can_be_removed')
    # ### end Alembic commands ###
