"""
Create unique constraint for Lead, Contact, and Follow-up tables.

Revision ID: ab42cdc0288a
Revises: 914876720f65
Create Date: 2023-07-04 12:50:27.152099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab42cdc0288a"
down_revision = "914876720f65"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_contact_id", "contact", ["id"])
    op.create_unique_constraint("uq_follow_up_id", "follow_up", ["id"])
    op.create_unique_constraint("uq_lead_id", "lead", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_lead_id", "lead", type_="unique")
    op.drop_constraint("uq_follow_up_id", "follow_up", type_="unique")
    op.drop_constraint("uq_contact_id", "contact", type_="unique")
    # ### end Alembic commands ###
