"""
Create Lead and Contact tables.

Revision ID: bad25e9f33b2
Revises: 863e35c5778d
Create Date: 2023-08-17 19:43:17.117048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad25e9f33b2'
down_revision = '863e35c5778d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('ref_number', sa.BigInteger(), nullable=False),
    sa.Column('loss_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('peril', sa.String(length=100), nullable=True),
    sa.Column('insurance_company', sa.String(length=100), nullable=True),
    sa.Column('policy_number', sa.String(length=50), nullable=True),
    sa.Column('claim_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_info', sa.String(length=100), nullable=True),
    sa.Column('instructions_or_notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('can_be_removed', sa.Boolean(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], name='fk_lead_assigned_to', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_lead_created_by_id'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='fk_lead_updated_by_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_number', name='uq_lead_ref_number')
    )
    op.create_table('lead_contact',
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('full_name_alt', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('email_alt', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('phone_number_alt', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('address_loss', sa.String(length=255), nullable=True),
    sa.Column('city_loss', sa.String(length=50), nullable=True),
    sa.Column('state_loss', sa.String(length=50), nullable=True),
    sa.Column('zip_code_loss', sa.String(length=20), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], name='fk_lead_contact_lead_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_contact')
    op.drop_table('lead')
    # ### end Alembic commands ###
