"""Create Unique Constraint on role table.

Revision ID: bc652f574b58
Revises: 30a098fc0266
Create Date: 2023-06-14 18:19:21.457640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc652f574b58'
down_revision = '30a098fc0266'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_role_id", 'role', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_role_id", 'role', type_='unique')
    # ### end Alembic commands ###
