"""
Create a Client table.

Revision ID: be701b1baa5c
Revises: cc6bbfeca2df
Create Date: 2023-08-22 06:37:16.329580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be701b1baa5c'
down_revision = 'cc6bbfeca2df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('ref_number', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('full_name_alt', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('email_alt', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('phone_number_alt', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('belongs_to', sa.UUID(), nullable=False),
    sa.Column('can_be_removed', sa.Boolean(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['belongs_to'], ['user.id'], name='fk_client_belongs_to', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_client_created_by_id'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='fk_client_updated_by_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number', name='uq_client_phone_number'),
    sa.UniqueConstraint('ref_number', name='uq_client_ref_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
