"""Create a model for user's personal files

Revision ID: c46ca6f934ab
Revises: 32e5974e9f66
Create Date: 2025-02-04 14:09:56.222904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c46ca6f934ab'
down_revision = '32e5974e9f66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_personal_file',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=150), nullable=False),
    sa.Column('expiration_date', sa.String(length=150), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['file.id'], name='fk_user_personal_file_id'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='fk_user_personal_file_owner_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_personal_file')
    # ### end Alembic commands ###
