"""
Create a Client Task table.

Revision ID: c70f63830082
Revises: fc678861de96
Create Date: 2023-08-26 10:45:11.490110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70f63830082'
down_revision = 'fc678861de96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='fk_client_task_client_id'),
    sa.ForeignKeyConstraint(['id'], ['user_task.id'], name='fk_client_task_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_task')
    # ### end Alembic commands ###
