"""
Create a Lead Task table.

Revision ID: cc6bbfeca2df
Revises: 81553430a0e9
Create Date: 2023-08-19 19:52:35.589951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6bbfeca2df'
down_revision = '81553430a0e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user_task.id'], name='fk_lead_task_id'),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], name='fk_lead_task_lead_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_task')
    # ### end Alembic commands ###
