"""
Update Comment table text column.

Revision ID: cf2c3bcf5d46
Revises: 583d7a2d08ee
Create Date: 2024-10-01 14:00:51.487560

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf2c3bcf5d46"
down_revision = "583d7a2d08ee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comment", "text", existing_type=sa.VARCHAR(length=500), type_=sa.Text
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comment", "text", existing_type=sa.Text, type_=sa.VARCHAR(length=500)
    )
    # ### end Alembic commands ###
