"""
Create a table for template files.

Revision ID: d4ba687ad171
Revises: 5f64f38b3836
Create Date: 2024-04-29 12:29:03.463010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ba687ad171'
down_revision = '5f64f38b3836'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_file',
    sa.Column('state', sa.String(length=5), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['file.id'], name='fk_template_file_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_file')
    # ### end Alembic commands ###
