"""
Create a Client Comment table.

Revision ID: d9992ee15e7d
Revises: be701b1baa5c
Create Date: 2023-08-23 18:59:11.932724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9992ee15e7d'
down_revision = 'be701b1baa5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_comment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='fk_client_comment_client_id'),
    sa.ForeignKeyConstraint(['id'], ['comment.id'], name='fk_client_comment_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_comment')
    # ### end Alembic commands ###
