"""

Create Claim and Claim Contact tables.

Revision ID: d9e4934aad3c
Revises: 28ec2678e5c5
Create Date: 2023-09-06 07:17:06.622424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e4934aad3c'
down_revision = '28ec2678e5c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('ref_number', sa.BigInteger(), nullable=False),
    sa.Column('loss_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('peril', sa.String(length=100), nullable=True),
    sa.Column('insurance_company', sa.String(length=100), nullable=True),
    sa.Column('policy_number', sa.String(length=50), nullable=True),
    sa.Column('fee_type', sa.String(length=20), nullable=True),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('claim_number', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_info', sa.String(length=100), nullable=True),
    sa.Column('current_phase', sa.String(length=50), nullable=False),
    sa.Column('instructions_or_notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('can_be_removed', sa.Boolean(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], name='fk_claim_assigned_to', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='fk_claim_client_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_claim_created_by_id'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='fk_claim_updated_by_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_number', name='uq_claim_ref_number')
    )
    op.create_table('claim_contact',
    sa.Column('address_loss', sa.String(length=255), nullable=True),
    sa.Column('city_loss', sa.String(length=50), nullable=True),
    sa.Column('state_loss', sa.String(length=50), nullable=True),
    sa.Column('zip_code_loss', sa.String(length=20), nullable=True),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name='fk_claim_contact_claim_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_contact')
    op.drop_table('claim')
    # ### end Alembic commands ###
