"""
Create a Claim File table.

Revision ID: dc1949bd4fd6
Revises: 8b71e848dd03
Create Date: 2023-09-09 11:15:00.251681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1949bd4fd6'
down_revision = '8b71e848dd03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_file',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name='fk_claim_file_claim_id'),
    sa.ForeignKeyConstraint(['id'], ['file.id'], name='fk_claim_file_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_file')
    # ### end Alembic commands ###
