"""
Remove unique phone number constraint from the client table.

Revision ID: ddb7c81fbb7c
Revises: 344405662316
Create Date: 2024-02-09 18:41:55.108907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb7c81fbb7c'
down_revision = '344405662316'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint('uq_client_phone_number', 'client', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_client_phone_number', 'client', ['phone_number'])
    op.alter_column('client', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
