"""
Alter Source column of a Lead table.

Revision ID: df42d462acd2
Revises: 3df5164b9f31
Create Date: 2024-06-27 19:03:55.742145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df42d462acd2'
down_revision = '3df5164b9f31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lead", sa.Column("source_temp", sa.UUID(), nullable=True))
    op.drop_column("lead", "source")
    op.alter_column(
        "lead", "source_temp", new_column_name="source", existing_type=sa.UUID()
    )
    op.create_foreign_key('fk_lead_source', 'lead', 'user', ['source'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_lead_source', 'lead', type_='foreignkey')
    op.add_column(
        "lead", sa.Column("source_temp", sa.String(length=30), nullable=True)
    )
    op.drop_column("lead", "source")
    op.alter_column(
        "lead",
        "source_temp",
        new_column_name="source",
        existing_type=sa.String(length=30),
    )
    # ### end Alembic commands ###
