"""
Create Claim Collaborator table.

Revision ID: ea8a94ed109c
Revises: 08c0c5793874
Create Date: 2024-07-08 21:21:00.023800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8a94ed109c'
down_revision = '08c0c5793874'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_collaborator',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name='fk_claim_collaborator_claim_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_claim_collaborator_user_id'),
    sa.PrimaryKeyConstraint('claim_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_collaborator')
    # ### end Alembic commands ###
