"""
Create a Client File table.

Revision ID: fc678861de96
Revises: d9992ee15e7d
Create Date: 2023-08-24 16:34:03.944895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc678861de96'
down_revision = 'd9992ee15e7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_file',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='fk_client_file_client_id'),
    sa.ForeignKeyConstraint(['id'], ['file.id'], name='fk_client_file_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_file')
    # ### end Alembic commands ###
