# Base Python Image
FROM python:3.11-bullseye

# Setup current working directory
WORKDIR /app/

# Argument for Poetry version
ARG POETRY_VERSION

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python - --version ${POETRY_VERSION} && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

# Copy poetry.lock* in case it doesn't exist in the repo
COPY ./app/pyproject.toml ./app/poetry.lock* /app/

# Allow installing dev dependencies to run tests
ARG INSTALL_DEV
RUN bash -c "if [ ${INSTALL_DEV} == 'true' ] ; then poetry install --no-root ; else poetry install --no-root --without dev,test ; fi"

# For development, Jupyter remote kernel, Hydrogen
# Using inside the container:
# jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.custom_display_url=http://127.0.0.1:8888
ARG INSTALL_JUPYTER=false
RUN bash -c "if [ $INSTALL_JUPYTER == 'true' ] ; then pip install jupyterlab ; fi"

# Copy application source code
COPY ./app /app

# Setup Environment for Python
ENV PYTHONPATH=/app

# To force Celery to run workers as root
ENV C_FORCE_ROOT=1

# Change shell files mode
RUN chmod 755 ./celery-worker-start.sh

# Entrypoint command for the container
ENTRYPOINT ["bash", "./celery-worker-start.sh"]