#!/usr/bin/env python

"""Schema for Claim Communication — Carrier Messages, Client Messages, Internal Notes"""

import datetime
from uuid import UUID

from pydantic import BaseModel, Field


# Shared properties
class ClaimCommunicationBase(BaseModel):
    message_type: str | None = Field(
        default=None,
        description="Message type: carrier, client, or internal.",
    )
    subject: str | None = Field(default=None, description="Message subject (carrier messages).")
    body: str | None = Field(default=None, description="Message body text.")
    recipient_email: str | None = Field(default=None, description="Recipient email (carrier).")
    recipient_name: str | None = Field(default=None, description="Recipient name (carrier).")
    direction: str | None = Field(default="outbound", description="Direction: inbound or outbound.")
    channel: str | None = Field(default="portal", description="Channel: email, portal, note, system.")
    thread_id: UUID | None = Field(default=None, description="Parent message ID for threading.")
    is_system_generated: bool | None = Field(default=False, description="Auto-generated by system.")
    attachments_json: str | None = Field(default=None, description="JSON array of attachments.")

    can_be_removed: bool | None = Field(default=True, description="Can be removed?")


# Properties to receive via API on creation
class ClaimCommunicationCreate(BaseModel):
    message_type: str = Field(description="Message type: carrier, client, or internal.")
    subject: str | None = Field(default=None, description="Message subject.")
    body: str = Field(description="Message body text.")
    recipient_email: str | None = Field(default=None, description="Recipient email.")
    recipient_name: str | None = Field(default=None, description="Recipient name.")
    direction: str = Field(default="outbound", description="Direction.")
    channel: str = Field(default="portal", description="Channel.")
    thread_id: UUID | None = Field(default=None, description="Parent message for threading.")
    attachments_json: str | None = Field(default=None, description="Attachments JSON.")


# Internal create with claim_id + sender_id set
class ClaimCommunicationCreateDB(ClaimCommunicationCreate):
    claim_id: UUID = Field(description="The claim ID.")
    sender_id: UUID = Field(description="The sender user ID.")
    is_system_generated: bool = Field(default=False)


# Properties to receive via API on update
class ClaimCommunicationUpdate(BaseModel):
    subject: str | None = Field(default=None, description="Message subject.")
    body: str | None = Field(default=None, description="Message body text.")
    recipient_email: str | None = Field(default=None, description="Recipient email.")
    recipient_name: str | None = Field(default=None, description="Recipient name.")
    attachments_json: str | None = Field(default=None, description="Attachments JSON.")
    can_be_removed: bool | None = Field(default=None, description="Can be removed?")


# Properties to return via API
class ClaimCommunicationInDB(ClaimCommunicationBase):
    id: UUID | None = Field(description="Communication ID.")
    claim_id: UUID | None = Field(description="The claim ID.")
    sender_id: UUID | None = Field(description="The sender user ID.")

    can_be_removed: bool | None = Field(description="Can be removed?")
    is_removed: bool | None = Field(description="Is removed?")

    class Config:
        orm_mode = True


# Sender info nested
class SenderInfo(BaseModel):
    id: UUID
    first_name: str | None = None
    last_name: str | None = None
    email: str | None = None

    class Config:
        orm_mode = True


# Full response with timestamps and audit
class ClaimCommunication(BaseModel):
    id: UUID
    claim_id: UUID
    sender_id: UUID
    message_type: str
    subject: str | None = None
    body: str
    recipient_email: str | None = None
    recipient_name: str | None = None
    direction: str
    channel: str
    thread_id: UUID | None = None
    is_system_generated: bool
    attachments_json: str | None = None
    can_be_removed: bool | None = None
    is_removed: bool | None = None
    sender: SenderInfo | None = None
    created_at: datetime.datetime | None = None
    updated_at: datetime.datetime | None = None
    created_by: UUID | None = None
    updated_by: UUID | None = None

    class Config:
        orm_mode = True


# Summary for the communications tab
class ClaimCommunicationSummary(BaseModel):
    carrier_count: int = 0
    client_count: int = 0
    internal_count: int = 0
    total_count: int = 0
    last_carrier_date: datetime.datetime | None = None
    last_client_date: datetime.datetime | None = None
    last_internal_date: datetime.datetime | None = None
