import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';

import {
  ActiveClaimContribution,
  AdminOverviewView,
  AgentSimpleEarningsView,
  ClaimEarningsRow,
  EarningsTrendView,
  FinancialDetailView,
  NextExpectedPayoutView,
  RecentActivityItem,
  StatementPeriod,
  StatementView,
  Taxable1099View,
} from '../models/commission-engine.model';

/**
 * HTTP-backed data source for the commission engine.
 *
 * One method per engine selector. The FastAPI backend at /v1/commission does
 * the computation and returns view-model-shaped JSON; this service is a thin
 * HTTP boundary.
 *
 * Dev-user alias
 * ──────────────
 * When `devAutoLogin` is on, UserService returns a stub user with id
 * `dev_user`. Before every backend call, we swap that literal for Alice
 * Nguyen's deterministic seed UUID (generated by uuid5 in the seed script).
 * The backend sees a real UUID; the frontend keeps its demo stub.
 *
 * When real auth is wired (next session), UserService will return a real
 * UUID and this alias short-circuit will be inert.
 */

const DEV_USER_ID = 'dev_user';
// uuid5(NAMESPACE_DNS, 'rin-portal.commission.user.alice_nguyen')
// Must match the seed script at upa-portal/backend/app/scripts/seed_commission_engine.py.
const DEV_ALIAS_UUID = 'a88fe7c8-1982-5856-aa70-5efe96ece7c7';

function resolveUserId(userId: string): string {
  return userId === DEV_USER_ID ? DEV_ALIAS_UUID : userId;
}

@Injectable({ providedIn: 'root' })
export class CommissionEngineDataService {
  /**
   * Calls go through the ApiInterceptor which prefixes `environment.server`
   * (e.g. https://…railway.app/v1). So paths here start at `commission/…`.
   */
  private readonly base = 'commission';

  constructor(private readonly http: HttpClient) {}

  // ─── Per-agent selectors ──────────────────────────────────────────────

  getAgentSimpleEarnings$(userId: string): Observable<AgentSimpleEarningsView> {
    return this.http.get<AgentSimpleEarningsView>(
      `${this.base}/agent/${resolveUserId(userId)}/earnings`,
    );
  }

  getEarningsTrend$(userId: string): Observable<EarningsTrendView> {
    return this.http.get<EarningsTrendView>(
      `${this.base}/agent/${resolveUserId(userId)}/trend`,
    );
  }

  getRecentActivity$(userId: string, limit: number = 6): Observable<RecentActivityItem[]> {
    const params = new HttpParams().set('limit', String(limit));
    return this.http.get<RecentActivityItem[]>(
      `${this.base}/agent/${resolveUserId(userId)}/activity`,
      { params },
    );
  }

  getActiveClaimContributions$(userId: string): Observable<ActiveClaimContribution[]> {
    return this.http.get<ActiveClaimContribution[]>(
      `${this.base}/agent/${resolveUserId(userId)}/active-claims`,
    );
  }

  getClaimEarningsTable$(userId: string): Observable<ClaimEarningsRow[]> {
    return this.http.get<ClaimEarningsRow[]>(
      `${this.base}/agent/${resolveUserId(userId)}/ledger`,
    );
  }

  getNextExpectedPayout$(userId: string): Observable<NextExpectedPayoutView> {
    return this.http.get<NextExpectedPayoutView>(
      `${this.base}/agent/${resolveUserId(userId)}/next-payout`,
    );
  }

  getTaxable1099YTD$(userId: string, year?: number): Observable<Taxable1099View> {
    let params = new HttpParams();
    if (year !== undefined) params = params.set('year', String(year));
    return this.http.get<Taxable1099View>(
      `${this.base}/agent/${resolveUserId(userId)}/1099-ytd`,
      { params },
    );
  }

  getStatement$(userId: string, period: StatementPeriod): Observable<StatementView> {
    const params = new HttpParams()
      .set('type', period.type)
      .set('start', period.start)
      .set('end', period.end)
      .set('label', period.label);
    return this.http.get<StatementView>(
      `${this.base}/agent/${resolveUserId(userId)}/statement`,
      { params },
    );
  }

  getFinancialDetail$(userId: string): Observable<FinancialDetailView> {
    return this.http.get<FinancialDetailView>(
      `${this.base}/agent/${resolveUserId(userId)}/financial-detail`,
    );
  }

  // ─── Admin ────────────────────────────────────────────────────────────

  getAdminOverview$(): Observable<AdminOverviewView> {
    return this.http.get<AdminOverviewView>(`${this.base}/admin/overview`);
  }

  // ─── Claims ───────────────────────────────────────────────────────────

  listClaims$(): Observable<ClaimRowDTO[]> {
    return this.http.get<ClaimRowDTO[]>(`${this.base}/claims`);
  }

  getClaimBreakdown$(claimId: string): Observable<ClaimTwoSectionBreakdownDTO> {
    return this.http.get<ClaimTwoSectionBreakdownDTO>(
      `${this.base}/claims/${claimId}/breakdown`,
    );
  }

  recordGrossFee$(claimId: string, grossFee: number, ts?: string): Observable<ClaimDTO> {
    return this.http.post<ClaimDTO>(
      `${this.base}/claims/${claimId}/gross-fee`,
      { gross_fee: grossFee, ts: ts ?? null },
    );
  }

  // ─── Writes ───────────────────────────────────────────────────────────

  createClaim$(payload: CreateClaimPayload): Observable<ClaimDTO> {
    return this.http.post<ClaimDTO>(`${this.base}/claims`, payload);
  }

  issueAdvance$(payload: IssueAdvancePayload): Observable<AdvanceDTO> {
    return this.http.post<AdvanceDTO>(`${this.base}/advances`, payload);
  }

  issuePayout$(payload: IssuePayoutPayload): Observable<PayoutDTO> {
    return this.http.post<PayoutDTO>(`${this.base}/payouts`, payload);
  }

  getAdvanceStats$(userId: string, claimId?: string | null): Observable<AdvanceStatsDTO> {
    let params = new HttpParams();
    if (claimId) params = params.set('claim_id', claimId);
    return this.http.get<AdvanceStatsDTO>(
      `${this.base}/agent/${resolveUserId(userId)}/advance-stats`,
      { params },
    );
  }

  getAdvanceBalance$(userId: string): Observable<AdvanceBalanceDTO> {
    return this.http.get<AdvanceBalanceDTO>(
      `${this.base}/agent/${resolveUserId(userId)}/advance-balance`,
    );
  }
}

export interface AdvanceStatsDTO {
  user_id: string;
  claim_id: string | null;
  week_total: number;
  lifetime_total: number;
  this_claim_has_advance: boolean;
  weekly_cap: number;
  lifetime_cap: number;
  week_start: string;
  week_end: string;
}

export interface AdvanceBalanceDTO {
  user_id: string;
  outstanding: number;
}

export interface IssueAdvancePayload {
  user_id: string;
  amount: number | string;
  issued_at?: string | null;
  notes?: string | null;
  claim_id?: string | null;
  admin_override?: boolean;
}

export interface AdvanceDTO {
  id: string;
  user_id: string;
  amount: number;
  issued_at: string;
  repaid_amount: number;
  notes: string | null;
  claim_id: string | null;
}

export interface IssuePayoutPayload {
  user_id: string;
  amount: number | string;
  issued_at?: string | null;
  method?: string | null;
  reference?: string | null;
  claim_id?: string | null;
  offset_advances?: boolean;
}

export interface PayoutDTO {
  id: string;
  user_id: string;
  amount: number;
  issued_at: string;
  method: string | null;
  reference: string | null;
  claim_id: string | null;
}

export interface ClaimRowDTO extends ClaimDTO {
  stage_label: string;
  writing_agent_name: string;
  rvp_name: string | null;
  cp_name: string | null;
  // I3 — carrier divergence surface
  carrier_estimate_amount: number | null;
  estimate_divergence_flagged: boolean;
  estimate_divergence_percentage: number | null;   // 0.25 = 25%
  estimate_divergence_dollars: number | null;
}

export interface ClaimBucketDetail {
  bucket: 'WRITING_AGENT' | 'RVP_OVERRIDE' | 'CP_OVERRIDE';
  label: string;
  percent_of_field: number;
  percent_of_gross: number;
  amount: number;
  recipient_user_id: string | null;
}

export interface ClaimTwoSectionBreakdownDTO {
  claim_id: string;
  claim_ref: string;
  gross_fee: number;
  house: { percent_of_gross: number; amount: number };
  field_total: { percent_of_gross: number; amount: number };
  field_buckets: ClaimBucketDetail[];
}

export interface CreateClaimPayload {
  client_name: string;
  claim_type: 'residential' | 'commercial';   // J2 — required at intake
  writing_agent_id: string;                // DB column preserved; UI label is "Team Member"
  claim_number?: string | null;            // server auto-generates when omitted
  stage?: string;
  rvp_id?: string | null;                  // server auto-resolves from manager chain
  cp_id?: string | null;
  direct_cp?: boolean;
  // Structured address (required at UI, nullable at API for legacy /
  // machine clients). No `unit` field — operators include apt/suite
  // inline on street_address.
  street_address?: string | null;
  city?: string | null;
  state?: string | null;
  zip?: string | null;
  carrier?: string | null;
  loss_date?: string | null;
  loss_type?: 'FIRE' | 'WATER' | 'WIND' | 'STORM' | 'THEFT' | 'OTHER' | null;
  notes?: string | null;
  // Damage estimate — drives advance tier at issue time (B4).
  estimate_amount?: number | string | null;
}

export interface ClaimDTO {
  id: string;
  client_name: string;
  claim_type: 'residential' | 'commercial';
  claim_number: string;
  stage: string;
  gross_fee: number;
  estimate_amount: number | null;
  writing_agent_id: string;
  rvp_id: string | null;
  cp_id: string | null;
  direct_cp: boolean;
  property_address: string | null;   // legacy free-form
  street_address: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  carrier: string | null;
  loss_date: string | null;
  loss_type: string | null;
  notes: string | null;
  created_at: string;
}
